name: "Setup Pixi Environment"
description: "Sets up pixi with common configuration"
inputs:
  version:
    description: "Pixi version https://github.com/prefix-dev/setup-pixi"
    required: false
    default: "v0.9.0"
  environments:
    description: "Pixi environments to setup"
    required: false
    default: "default"
  activate-environment:
    description: "Environment to activate"
    required: false
    default: "default"
  run-install:
    description: "Whether to run pixi install"
    required: false
    default: "true"
  locked:
    description: "Whether to run pixi install --locked"
    required: false
    default: "false"
  frozen:
    description: "Whether to run pixi install --frozen"
    required: false
    default: "true"
  cache:
    description: "Whether to use cache"
    required: false
    default: "false"
  post-cleanup:
    description: "Whether to run post cleanup"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: prefix-dev/setup-pixi@${{ inputs.version }}
      with:
        environments: ${{ inputs.environments }}
        activate-environment: ${{ inputs.activate-environment }}
        run-install: ${{ inputs.run-install }}
        locked: ${{ inputs.locked }}
        frozen: ${{ inputs.frozen }}
        cache: ${{ inputs.cache }}
        post-cleanup: ${{ inputs.post-cleanup }}
